### PR TITLE
Card Component, Toast Component refactor

### PR DESCRIPTION
**Pull request by bharati-21**
Refactored toast and card component
- Removed toast and card from docs/index.html
- Edited horizontal card styles
- Removed padding and margin from both card, toast styles. Added util classes for padding and margin in HTML code.
- Deleted docs/index.html file

### CODE REVIEW

**Review by NeerajVodala — APPROVED** [review]
Looks good to me.
All the best.

**Comment by bharati-21** [comment]
> Looks good to me. All the best.


Thank you for your review

**Review by shashikantmaurya0007 — APPROVED** [review]
Your code looks so neat.i like how you have created variables for tiny things.looking your code inspire me to write clean code:)..good to merge 👍

**Comment by bharati-21** [comment]
> Your code looks so neat.i like how you have created variables for tiny things.looking your code inspire me to write clean code:)..good to merge 👍

Thank you for your review!

**Pull request merged**
