### PR TITLE
P0 - Card Component 

### PR DESCRIPTION
**Pull request by bharati-21**
- Styled card component with the following variations and added to the docs:
  - Vertical Card
  - Card with Badge
  - Card with Dismiss Button
  - Card with Overlay Text
  - Card with only Text
  - Horizontal Card
  - Card with Shadow

### CODE REVIEW

**Review by shashikantmaurya0007 — APPROVED** [review]
Card looks clean and beautiful.it is mobile responsive too.your effort are evident from the Ui.you can merge this :)

**Review by zabihshaik — APPROVED** [review]
Everything looks good. Good to go.

**Review by sonishreyas — APPROVED** [review]
Looks good to be merged

**Comment by bharati-21** [comment]
> Card looks clean and beautiful.it is mobile responsive too.your effort are evident from the Ui.you can merge this :)

Thank you for your time and review!

**Comment by bharati-21** [comment]
> Everything looks good. Good to go.

Thank you for your time and review!

**Comment by bharati-21** [comment]
> Looks good to be merged

Thank you for your time and review!

**Pull request merged**
