### PR TITLE
P1 - Modal and Navigation Component

### PR DESCRIPTION
**Pull request by bharati-21**
- Created a simple modal component with a modal text and 2 action buttons.
- Created a navigation component that's responsive across devices with a logo, search bar, nav links, and an optional hamburger in smaller screens.

### CODE REVIEW

**Review by himadri2110 — APPROVED** [review]
Looks clean!

**Comment by bharati-21** [comment]
> Looks clean!

Thank you!

**Review by vidhi-thakur — APPROVED** [review]
looks good to me

**Comment by bharati-21** [comment]
> looks good to me

Thank you!

**Pull request merged**
