### PR TITLE
P1- Rating, P2- Slider Components

### PR DESCRIPTION
**Pull request by bharati-21**
- Added Rating component with read-only rating badge and star product rating.
- Added simple custom styles range slider

### CODE REVIEW

**Review by shashikantmaurya0007 — APPROVED** [review]
Looks good to be nerged:)

**Review by sagargse — APPROVED** [review]
All looks good to me you can merge.

**Comment by pariyar07** [comment]
Would be better to review if you add the screenshot or any kind of preview. Anyways code looks clean and good to merge.

**Comment by bharati-21** [comment]
> All looks good to me you can merge.

Thank you!

**Comment by bharati-21** [comment]
> Looks good to be nerged:)

Thank you!

**Comment by bharati-21** [comment]
> Would be better to review if you add the screenshot or any kind of preview. Anyways code looks clean and good to merge.

Okay, I shall keep this in mind for future PRs. 👍🏽 
But here's the deploy preview - https://deploy-preview-19--elixir-ui.netlify.app/docs/rating/
https://deploy-preview-19--elixir-ui.netlify.app/docs/slider/

Thank you!

**Pull request merged**
