### PR TITLE
P0 - Input Component, P1 - Typography Component

### PR DESCRIPTION
**Pull request by bharati-21**
# Input Component
## Styled and added input components to documentation. Created the following variations for input component-
   - Default input
   - Success, warning, and error validation input
   - Default textbox
   - Succes, warning and error validation textbox

# Typography Component
## Styled and added typography component to the documentation page. Created the following variations - 
  - Heading utilities
  -  Text Utilities
  - Colored Text Utilities
  - Aligned Text Utilities

### CODE REVIEW

**Review by chanchal16 — APPROVED** [review]
looks good to me!

**Comment by bharati-21** [comment]
> looks good to me!

Thank you for your time and review 👍🏽

**Review by sonishreyas — APPROVED** [review]
Looks good to me

**Comment by bharati-21** [comment]
> Looks good to me

Thank you for your time and review! 👍🏽

**Pull request merged**
