### PR TITLE
Avatar component refactor

### PR DESCRIPTION
**Pull request by bharati-21**
Removed margin from avatar class styles. Added margin util class in the avatar container
Renamed .text-avatar to .avatar-text and .square to .avatar-square
Removed avatar component from docs/index.html to docs/avatar/index.html
Pulled alert changes from dev branch

### CODE REVIEW

**Review by manojasarsa — APPROVED** [review]
Looks good, Just a quick suggestion: You can add top/bottom margin to "Get-Started" and "Documentation" buttons on Home page.

**Review by zabihshaik — COMMENTED** [review]
Everything looks good.

**Comment by bharati-21** [comment]
> Looks good, Just a quick suggestion: You can add top/bottom margin to "Get-Started" and "Documentation" buttons on Home page.

Yes, I'm yet to refactor that page. Working component by component.
Thank you for your review!

**Comment by bharati-21** [comment]
> Everything looks good.

Thank you for your review!

**Pull request merged**
