### PR TITLE
Flex Utility Classes Refacttor 

### PR DESCRIPTION
**Pull request by bharati-21**
Edit flex class names from BEM convention to hyphenated names.
E.g. `flex--row` to `flex-row`

### CODE REVIEW

**Review by aurobindoGupta — APPROVED** [review]
good work !!

**Review by TejasShekar — APPROVED** [review]
Changes have been made as mentioned in the PR description. 
Merge 👍.

**Review by AtulHande03a — APPROVED** [review]
looks good!!!

**Comment by bharati-21** [comment]
> good work !!

Thank you!

**Comment by bharati-21** [comment]
> > good work !!
> 
> Thank you!

Thank you

**Comment by bharati-21** [comment]
> Changes have been made as mentioned in the PR description. Merge 👍.

Thank you!

**Comment by bharati-21** [comment]
> looks good!!!

Thank you!

**Pull request merged**
