### PR TITLE
Badge Component Refactor

### PR DESCRIPTION
**Pull request by bharati-21**
Refactored badge component 
- Moved badge component from docs/index.html to docs/badge/index.html
- Removed padding, margin from stylesheet and added utility classes in HTML code
- Renamed .status-badge to .badge-status classname
- Changed accent color to secondary color
- Edited .square to .avatar-square class name

### CODE REVIEW

**Review by NeerajVodala — APPROVED** [review]
Everything looks good to me.
All the best.

**Review by ravikumar0403 — APPROVED** [review]
Looks good to me

**Comment by bharati-21** [comment]
> Everything looks good to me. All the best.

Thank you for your review!

**Comment by bharati-21** [comment]
> Looks good to me

Thank you for your review!

**Pull request merged**
