### PR TITLE
P0 - Badge and Button Components

### PR DESCRIPTION
**Pull request by bharati-21**
- Created and styled badge component. Added it to the docs page.
  - The badge component has the following variations - availability status badge, notification status badge, simple squared, and round pill badge.
- Created and styled button component. Added it to the docs page.
  - The button component has the following variations in primary and secondary color - solid, outline, link, text-icon, and icon-only buttons.
  - Another variation is floating action buttons that come only in a primary color.
  - All the buttons can be disabled which disables all pointer events.

### CODE REVIEW

**Review by nyyshaaa — COMMENTED** [review]
CSS spaces reusability is so cool. Looks great!

**Comment by shashikantmaurya0007** [comment]
looks good to me the just one suggestion the text component in component index gets crop when you scroll the page

**Review by Creator-singh — APPROVED** [review]
looks good to go just do the above changes requested.

**Review by shashikantmaurya0007 — APPROVED** [review]

**Comment by TejasShekar** [comment]
Everything looks great. One suggestion would be to make the buttons actions null so that the page doesn't reload when a button component example is clicked.

**Comment by bharati-21** [comment]
> CSS spaces reusability is so cool. Looks great!

Thank you!

**Comment by bharati-21** [comment]
> looks good to me the just one suggestion the text component in component index gets crop when you scroll the page

Thank you. Yes, yet to make the page responsive.

**Comment by bharati-21** [comment]
> Everything looks great. One suggestion would be to make the buttons actions null so that the page doesn't reload when a button component example is clicked.

Yes, thank you! Will work on this.

**Comment by bharati-21** [comment]
Merging PR from badge-button branch to development.

**Pull request merged**
